name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Import workspace"
        uses: actions/checkout@v1

      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "src/jenv.ps1"
          find: "\\$JENV_VERSION = \"(.+?)\""
          replace: "world"
          regex: true

      - name: "Zip files"
        run: "zip -r JEnv.zip src/ jenv.bat java.bat"

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: JEnv.zip
